#!/bin/bash
if [[ -f /etc/redhat-release ]]; then
    release="centos"
  elif grep -q -E -i "debian|ubuntu" /etc/issue; then
    release="debian"
  elif grep -q -E -i "centos|red hat|redhat" /etc/issue; then
    release="centos"
  elif grep -q -E -i "Arch|Manjaro" /etc/issue; then
    release="arch"
  elif grep -q -E -i "debian|ubuntu" /proc/version; then
    release="debian"
    echo "当前系统debian"
  elif grep -q -E -i "centos|red hat|redhat" /proc/version; then
    release="centos"
  else
    if grep -q -E -i "Alpine" /proc/version; then
	Alpine="True"
    echo "当前系统Alpine"
    else
    echo -e "NodeStatus Client 暂不支持该 Linux 发行版"
    exit 1
    fi
fi